### ISSUE TITLE
Question: why MongoDB

### ISSUE THREAD

**Issue by otisg** [diogolmenezes/elastic-butler#1]
I'm curious why you chose to add MongoDB to the mix considering a person using Elastic Butler already has a data store Butler could use - ES.

**Comment by diogolmenezes** [comment]
Hi @otisg !

Actually all the body of recipes that will be executed are stored at mongo database.

Butler reads the recipes, schedule and execute the job.

On recipes you set the path to the target ES, for example.

You could have many recipes looking to many different elastic searchs endpoints.

Your suggestion is to store recipes inside ES? What about we have many ES hosts to monitor?

Thanks for comment.

**Comment by otisg** [comment]
> Your suggestion is to store recipes inside ES? 

Yes.  Why not?

> What about we have many ES hosts to monitor?

Why is this a problem?  If you can store many recipes in Mongo you will also be able to store them in ES.

**Comment by wcchristian** [comment]
> What about we have many ES hosts to monitor?

Even if there are many hosts to monitor, should be no problem to have a  "master" or something signified to hold the configuration. This way even if people don't want to store the config in one of their existing ES hosts they could just spin another one. That way we simplify the stack.

I'd be willing to take a crack at fixing this up if thats cool.

**Comment by wcchristian** [comment]
I suggest we add elastic as a config store option and leave mongo stuff as is so it works either way.

**Comment by diogolmenezes** [comment]
Nice, lets work on it!

**Comment by wcchristian** [comment]
Cool. I might do some tinkering tonight and see if I can come up with a PR or two for ya!

**Comment by diogolmenezes** [comment]
Hi! @otisg now elastic-butler uses elastic search to store the recipes and executions. Thanks @wcchristian  for you pull request!
