### ISSUE TITLE
Is there support for...

### ISSUE THREAD

**Issue by zhongxian93** [diogolmenezes/elastic-butler#7]
Hi everyone i have just started to try elastic-butler 
after trying to start butler using `npm start` and trying out `butler docker` 
i start seeing non window command like `sudo `and `clear`

i start wondering if:
there is support for windows & is there support for elasticsearch if i already have it running in a docker container

**Comment by diogolmenezes** [comment]
Hey!

Yes, there is support for elasticsearch if you already have it running in a docker container. You only have to configure the elastic url in your recipe.

`"elasticsearch": "http://yourelastic:9200"`
