### ISSUE TITLE
Multiple email addresses?

### ISSUE THREAD

**Issue by CrispyCB** [diogolmenezes/elastic-butler#8]
How would I set up emailing to multiple email addresses? Just add a comma after each email address? Or can each recipe only email one person?

**Comment by diogolmenezes** [comment]
Hey!

elastic-butler mail class (https://github.com/diogolmenezes/elastic-butler/blob/master/worker/senders/gmail.js) uses nodemailer lib to send mails.

Nodemaile acept multiple mails so you can use it.

to: "bar@example.com, baz@example.com", // list of receivers
