### ISSUE TITLE
Invalid Login Error

### ISSUE THREAD

**Issue by CrispyCB** [diogolmenezes/elastic-butler#9]
I keep getting this error:

Butler => Error executing the action for recipe [test] [test-recipe] Error: Invalid login: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials i1sm9267675qtb.7 - gsmtp

I have the right credentials listed in my env.json - do you know what might be causing this error, @diogolmenezes?

Thanks!

**Comment by diogolmenezes** [comment]
You solved it ? @CrispyCB

**Comment by CrispyCB** [comment]
Yep!
